create table
  public.links (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    song_id bigint not null,
    platform_id bigint not null,
    song_url text not null,
    constraint links_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.platforms (
    id bigint generated by default as identity,
    platform_name text not null,
    platform_url text not null,
    constraint platforms_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.songs (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    song_name text not null,
    artist text not null,
    album text not null,
    constraint songs_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.users (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    password text not null default 'password'::text,
    platform_id bigint not null default '1'::bigint,
    constraint users_pkey primary key (id),
    constraint users_platform_id_fkey foreign key (platform_id) references platforms (id)
  ) tablespace pg_default;